apiVersion: v1
kind: Pod                    # type of object
metadata:
  name: webapp-pod           # name of pod
  labels:
    application: webappln    # Matching key:value pair exist in service select this pod to connect.
spec:                        # This section list containers
  containers:
  - name: webapp             # name of container, not really matters
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0       # image for container
    #command and Argument - In above image, nginx is using port 80 and most of containers comes with command
    #so these two options are not required though exist for container. 